import { Schema, model, InferSchemaType, HydratedDocument } from 'mongoose';

export const MESSAGE_MAX = 2000;

/** One member of a conversation, with their personal read state. */
const memberSchema = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    role: { type: String, enum: ['owner', 'teacher', 'parent'], required: true },
    unread: { type: Number, default: 0 },
    lastReadAt: { type: Date, default: () => new Date(0) },
  },
  { _id: false },
);

/** A 1-to-1 chat between two people of the same institute. */
const conversationSchema = new Schema(
  {
    instituteId: { type: Schema.Types.ObjectId, ref: 'Institute', required: true, index: true },
    /** Sorted pair of user ids — guarantees one conversation per pair. */
    key: { type: String, required: true },
    members: { type: [memberSchema], required: true },
    lastMessage: {
      text: String,
      senderId: { type: Schema.Types.ObjectId, ref: 'User' },
      at: Date,
    },
  },
  { timestamps: true },
);
conversationSchema.index({ instituteId: 1, key: 1 }, { unique: true });
conversationSchema.index({ 'members.userId': 1, updatedAt: -1 });

export type ConversationT = InferSchemaType<typeof conversationSchema>;
export type ConversationDoc = HydratedDocument<ConversationT>;
export const Conversation = model('Conversation', conversationSchema);

const messageSchema = new Schema(
  {
    instituteId: { type: Schema.Types.ObjectId, ref: 'Institute', required: true },
    conversationId: { type: Schema.Types.ObjectId, ref: 'Conversation', required: true },
    senderId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    text: { type: String, required: true, maxlength: MESSAGE_MAX },
    /** Id generated by the browser so a retried send never creates a duplicate. */
    clientId: String,
  },
  { timestamps: true },
);
messageSchema.index({ conversationId: 1, createdAt: -1, _id: -1 });
messageSchema.index({ senderId: 1, clientId: 1 }, { unique: true, partialFilterExpression: { clientId: { $type: 'string' } } });

export type MessageT = InferSchemaType<typeof messageSchema>;
export const Message = model('Message', messageSchema);
